name: View pom.xml Content

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  view_pom_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: View pom.xml Content
        run: |
          cd ${{ github.workspace }}  # Di chuyển đến thư mục github.workspace (thường là D:\a)
          cat pom.xml  # In ra nội dung của pom.xml
